### ISSUE TITLE
Posthog Flutter SDK is not sending any events

### ISSUE THREAD

**Issue by bcheidemann-kmbal** [PostHog/posthog-flutter#128]
### Version

4.6.0

### Steps to Reproduce

Reproduction repo: https://github.com/bcheidemann/flutter_posthog_test

1. Initialise a new flutter project
2. Run `flutter pub add posthog_flutter`
3. Update `Info.plist` and `Podfile` according to docs (https://posthog.com/docs/libraries/flutter)
4. Replace `POSTHOG_HOST` with unique https://webhook.site/ URL
5. Add `await Posthog().capture(eventName: 'Example');` to app
6. Start an iOS Simulator (iPhone 16 Pro Max / iOS 18.1)
7. Run `flutter run` and select the simulator
8. Trigger call to `capture`
9. Observe no events are received by webhook.site

### Expected Result

Events should be received

### Actual Result

No events are received

**Comment by marandaneto** [comment]
Hello,

Add this to your plist as well:

```
	<key>com.posthog.posthog.DEBUG</key>
    <true/>
```

So you can check in your Xcode console logs if the events are sent to the server and if there were no errors:

You should see something for example:

> [PostHog] Sending batch of N events to PostHog
> [PostHog] Events sent successfully.
> [PostHog] Completed!

If that happens and you still don't see any events coming in, it's something with your self-hosted version since you are using the (webhook.site?).
I just tested your sample and everything is working fine with my project on PostHog cloud.

**Comment by bcheidemann-kmbal** [comment]
Hey @marandaneto, I'll test this and get back to you with the result.

Fwiw, I am using PostHog cloud, and am experiencing the same issue. [webhook.site](https://webhook.site/) is the service you recommend on your [Troubleshooting and FAQs guide](https://posthog.com/docs/product-analytics/troubleshooting) for testing if events are being sent.

**Comment by marandaneto** [comment]
@bcheidemann-kmbal https://github.com/PostHog/posthog-flutter/releases/tag/4.10.2
