### ISSUE TITLE
PosthogFlutterPlugin.java uses unchecked or unsafe operations.

### ISSUE THREAD

**Issue by alexprice12** [PostHog/posthog-flutter#23]
When I run `flutter run` I get the following error:

```
Note: /home/alex/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/posthog_flutter-2.0.3/android/src/main/java/com/posthog/posthog_flutter/PosthogFlutterPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/alex/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/posthog_flutter-2.0.3/android/src/main/java/com/posthog/posthog_flutter/PosthogFlutterPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
```

**Comment by 2x2xplz** [comment]
Same warnings on 3.1.0. 

Looking at the Java plugin source code, [Google recommends](https://docs.flutter.dev/release/breaking-changes/plugin-api-migration#upgrade-steps) continuing to support `registerWith` method whose parameter `PluginRegistry.Registrar` raises the Deprecation warning. Since this is a known deprecation left in for compatibility for older apps, this could potentially be annotated with `@SuppressWarnings("deprecation")`.

Two unchecked calls come from the `deepMerge` method which is unused in this package and posthog-android, so it can be safely removed. The remaining unchecked call comes from the line `payload.toBuilder().context(appendToContextMiddleware).build()`. This can be alleviated by verifying the concrete type of the abstract `BasePayload`. There is no change in functionality but it ensures the compiler can verify the correct concrete type. It's ugly but it works.

```java
//              BasePayload newPayload = payload.toBuilder()
//                .context(appendToContextMiddleware)
//                .build();
              BasePayload newPayload = null;
              // great opportunity to use Sealed Classes and ensure a comprehensive check
              if (payload instanceof AliasPayload) {
                newPayload = ((AliasPayload.Builder) payload.toBuilder()).context(appendToContextMiddleware).build();
              } else if (payload instanceof CapturePayload) {
                newPayload = ((CapturePayload.Builder) payload.toBuilder()).context(appendToContextMiddleware).build();
              } else if (payload instanceof GroupPayload) {
                newPayload = ((GroupPayload.Builder) payload.toBuilder()).context(appendToContextMiddleware).build();
              } else if (payload instanceof IdentifyPayload) {
                newPayload = ((IdentifyPayload.Builder) payload.toBuilder()).context(appendToContextMiddleware).build();
              } else if (payload instanceof ScreenPayload) {
                newPayload = ((ScreenPayload.Builder) payload.toBuilder()).context(appendToContextMiddleware).build();
              }
```
Making the three changes above (annotating `registerWith()`, removing `deepMerge()`, changing `newPayload` code) will eliminate compiler warnings.

Separately, I did not perform any comprehensive checks or tests but this method near the bottom of the file is concerning:
```java
  @SuppressWarnings("unchecked")
  private Options buildOptions(HashMap<String, Object> optionsData) {
    Options options = new Options();
    return options;
  }
```
As you can see, the `optionsData` param is never used, this method simply returns a blank `Options` object.

**Comment by marandaneto** [comment]
https://github.com/PostHog/posthog-flutter/pull/60 would address this issue
