### ISSUE TITLE
apk!libflutter.so crash

### ISSUE THREAD

**Issue by jatin09univest** [PostHog/posthog-flutter#67]
### Version

3.3.0

### Steps to Reproduce

After adding PostHog, the crash count in Firebase Crashlytics has increased, showing the error split_config.arm64_v8a.apk!libflutter.so

### Expected Result

.   

### Actual Result

.

**Comment by marandaneto** [comment]
@jatin09univest The PH Flutter SDK does not bundle native libraries (besides the Dart compiled code of course which is a native library), the linked library is Flutter itself.
It's probably a coincidence that you're getting these errors after adding PostHog.

For example https://stackoverflow.com/questions/73862881/libflutter-so-and-split-config-arm64-v8a-apklibflutter-so
Most likely this issue is automatically solved when adding `abiFilters` (just a hunch).

Happy to reopen this issue if you have more context or ideas on how the PH SDK could be causing this.
