### ISSUE TITLE
add the function to check if the user has identified

### ISSUE THREAD

**Issue by shinyo17** [PostHog/posthog-flutter#9]
Hi!
I want to know that user has identified.
and I want to know  user's property like email, name.
Can you create this function in flutter package?

**Comment by Twixes** [comment]
Hey! I think this package may not be right place for this: this feature would involve querying PostHog's API as a logged in user (using a full-access _personal_ API key instead of the write-only _project_ API key). For now we don't plan to support this here. In the meantime I'd suggest you write your own ad hoc function in your app to query the [person PostHog endpoint](https://posthog.com/docs/api/people) the way you need.

**Comment by shinyo17** [comment]
@Twixes Ohh Thanks!
